language: ruby
rvm:
  - 2.7

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler 

after_success: |
    sudo pip install ghp-import && \
    ghp-import _site && \
    git push -qf https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages