title: Luigi Russo
description: Personal website.
baseurl: ""
url: "https://lrusso96.github.io"


permalink: /posts/:title.html

# Author Settings
author: Luigi Russo # add your name
about-author: MSc. Computer Eningeering student. # add description
social-github: lrusso96 # add your Github handle
social-email: russo.1699981@studenti.uniroma1.it # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-last-modified-at

collections:
  sections:
    output: true

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
